version: "3.1"

services:
  db:
    image: mongo:6.0
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  api:
    image: node:16
    container_name: api
    restart: always
    env_file:
     - .env
    depends_on:
      - db
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
